<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Aloqa' => 'Contact',
    'Bosh sahifa' => 'Home',
    'Bosh sahifa /' => 'Home /',
    'English' => 'English',
    'KO\'P O\'QILGAN YANGILIKLAR' => 'MOST READ NEWS',
    'Karta' => 'Map',
    'O\'ZBEK' => 'O \' ZBEK',
    'Tilni o\'zgartirish' => 'Change language',
    'Tourism Yangiliklari' => 'Tourism News',
    'YANGILIKLAR' => 'NEWS',
    'Yangiliklar' => 'News',
    'РУССКИЙ' => 'RUSSIAN',
    'Batafsil' => '',
    'Tourism Mediya' => '',
    'salom' => '@@@@',

    'Ism'=>'Name',
    'Familiya'=>'Surname',
    'Mavzu'=>'Subject',
    'Matin'=>'Text',

    "Bog‘lanish"=>"Contact",
    "Xabar yuborish"=>"Send a message",
    "Yuborish"=>"Send message",
    "Invest loyihalarini kartada joylashivi"=>"Placement of investment projects on the map",
];
