<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Aloqa' => 'Контакт',
    'Batafsil' => 'Еще',
    'Bosh sahifa' => 'Главный',
    'Bosh sahifa /' => 'Главный /',
    'English' => 'Английский',
    'KO\'P O\'QILGAN YANGILIKLAR' => 'САМЫЕ ЧИТАЕМЫЕ НОВОСТИ',
    'Karta' => 'Карта',
    'O\'ZBEK' => 'О \' ZBEK',
    'Tilni o\'zgartirish' => 'Изменить язык',
    'Tourism Yangiliklari' => 'Новости туризма',
    'YANGILIKLAR' => 'НОВОСТИ',
    'Yangiliklar' => 'Новости',
    'РУССКИЙ' => 'РУССКИЙ',
    'Tourism Mediya' => '',
    'salom' => '@@@@',

    'Ism'=>'Имя',
    'Familiya'=>'Фамилия',
    'Mavzu'=>'Предмет',
    'Matin'=>'Tекст',

    "Bog‘lanish"=>"Контакты",
    "Xabar yuborish"=>"Послать сообщение",
    "Yuborish"=>"Отправить",
    "Invest loyihalarini kartada joylashivi"=>"Размещение инвестиционных проектов на карте",
];
