<?php

namespace frontend\components;

use common\components\Config;
use frontend\assets\AppAsset;
use Yii;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\PjaxAsset;

class View extends \yii\web\View
{
    public $staticUrl;
    private $langs = [
        'ru' => 'Русский',
        'en' => 'English',
        'uz' => 'O\'zbek'
    ];
    public function init()
    {
        $this->staticUrl = $this->getAssetManager()->getBundle(AppAsset::className())->baseUrl;
        $this->registerJs("var globalVars = {s: '" . $this->staticUrl . "'};", self::POS_HEAD);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getImageUrl($name)
    {
        return $this->getAssetManager()->getBundle('\frontend\assets\AppAsset')->baseUrl . $name;
    }

    public function lang(){
        echo'<span>'.$this->langs[Yii::$app->language].'</span>
                  <div class="dropdown_lang">';
        $langs = $this->langs;
        unset($langs[Yii::$app->language]);
        foreach ($langs as $lang_code => $lang_title):
            echo '<a href="'.\yii\helpers\Url::current(['language' => $lang_code]).'">'.$lang_title.'</a>';
        endforeach;
        echo'</div>';
    }
}