<?php

namespace common\modules\menu\models;


use Yii;
use yii\caching\TagDependency;
use \yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\behaviors\SluggableBehavior;
//Системные
use oks\core\behaviors\DateTimeBehavior;
use oks\core\behaviors\UserBehavior;
//Файлы
use oks\filemanager\behaviors\FileModelBehavior;
use oks\filemanager\models\Files;
//Языки
use oks\langs\models\Langs;
use oks\langs\components\ModelBehavior;
/**
 * This is the model class for table "menu_items".
 *
 * @property int $menu_item_id Идентификатор
 * @property int $menu_id Меню
 * @property string $title Название
 * @property string $url Ссылка
 * @property int $sort Сортировка
 * @property int $menu_item_parent_id Родитель
 *
 * @property Menu $menu
 * @property MenuItems $menuItemParent
 * @property MenuItems[] $menuItems
 */
class MenuItems extends \yii\db\ActiveRecord
{
    const SCENARIO_SEARCH = "search";
    const STATUS_ACTIVE = 1;



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu_items';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['menu_id', 'sort', 'menu_item_parent_id'], 'default', 'value' => null],
            [['menu_id', 'sort', 'menu_item_parent_id'], 'integer'],
            [['url'], 'string'],
            [['title','icon'], 'string', 'max' => 500],
            [['menu_id'], 'exist', 'skipOnError' => true, 'targetClass' => Menu::className(), 'targetAttribute' => ['menu_id' => 'menu_id']],
            [['menu_item_parent_id'], 'exist', 'skipOnError' => true, 'targetClass' => MenuItems::className(), 'targetAttribute' => ['menu_item_parent_id' => 'menu_item_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'menu_item_id' => 'Menu Item ID',
            'menu_id' => 'Menu ID',
            'title' => __('Title'),
            'url' => __('Url'),
            'sort' => __('Sort'),
            'icon' => __('Icon'),
            'menu_item_parent_id' => 'Menu Item Parent ID',
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenu()
    {
        return $this->hasOne(Menu::className(), ['menu_id' => 'menu_id'])->orderBy(['sort' => SORT_ASC])->inverseOf('menuItems');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenuItemParent()
    {
        return $this->hasOne(MenuItems::className(), ['menu_item_id' => 'menu_item_parent_id'])->orderBy(['sort' => SORT_ASC])->inverseOf('menuItems');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenuItems()
    {
        return $this->hasMany(MenuItems::className(), ['menu_item_parent_id' => 'menu_item_id'])->orderBy(['sort' => SORT_ASC])->inverseOf('menuItemParent');
    }


    /**
     * @inheritdoc
     * @return MenuItemsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new MenuItemsQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        \yii\caching\TagDependency::invalidate(Yii::$app->cache,'menu');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterDelete()
    {
        \yii\caching\TagDependency::invalidate(Yii::$app->cache,'menu');
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }


}
